<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Core\MeuValorLiquido.Core.csproj" />
    <ProjectReference Include="..\Shared\MeuValorLiquido.Shared.csproj" />
    <ProjectReference Include="..\Modules\Calculators\MeuValorLiquido.Modules.Calculators.csproj" />
    <ProjectReference Include="..\Modules\Content\MeuValorLiquido.Modules.Content.csproj" />
    <ProjectReference Include="..\Modules\Contact\MeuValorLiquido.Modules.Contact.csproj" />
    <ProjectReference Include="..\Modules\Newsletter\MeuValorLiquido.Modules.Newsletter.csproj" />
    <ProjectReference Include="..\Modules\Ads\MeuValorLiquido.Modules.Ads.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
